In [14]:
import numpy as np

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def layer_norm(x, gamma, beta, epsilon=1e-6):
    mean = np.mean(x, axis=-1, keepdims=True)
    variance = np.var(x, axis=-1, keepdims=True)
    x_normalized = (x - mean) / np.sqrt(variance + epsilon)
    return gamma * x_normalized + beta

In [8]:
d_model = 64
max_seq_len = 10
batch_size = 2

input_embeddings = np.random.rand(batch_size, max_seq_len, d_model)

position = np.arange(max_seq_len)[:, np.newaxis]
div_term = np.exp(np.arange(0, d_model, 2) * -(np.log(10000.0) / d_model))
pe = np.zeros((max_seq_len, d_model))
pe[:, 0::2] = np.sin(position * div_term);
pe[:, 1::2] = np.cos(position * div_term)
pe = pe[np.newaxis, :, :]

encoder_input = input_embeddings + pe
display(encoder_input)

array([[[ 2.71419577e-01,  1.15971050e+00,  9.66230904e-01, ...,
          1.85068664e+00,  7.29099346e-01,  1.14142302e+00],
        [ 1.51426213e+00,  7.29362877e-01,  1.35271826e+00, ...,
          1.57554722e+00,  2.07609174e-01,  1.12852196e+00],
        [ 1.29530789e+00,  2.87770905e-01,  1.69397994e+00, ...,
          1.77397667e+00,  3.17829418e-02,  1.05465118e+00],
        ...,
        [ 1.57220437e+00,  1.71571685e+00, -6.65671627e-02, ...,
          1.35996791e+00,  7.91001173e-01,  1.48774440e+00],
        [ 1.46964541e+00, -2.27592035e-02,  4.94619493e-02, ...,
          1.75115021e+00,  8.92546572e-01,  1.19505607e+00],
        [ 5.66840945e-01, -6.40402804e-01,  1.18226985e+00, ...,
          1.70388396e+00,  4.73832682e-01,  1.93489698e+00]],

       [[ 2.20828538e-01,  1.34043799e+00,  1.78504592e-02, ...,
          1.09368954e+00,  2.27484424e-01,  1.62110875e+00],
        [ 1.34265797e+00,  6.71739900e-01,  6.84814600e-01, ...,
          1.52238943e+00,  5.44278850e

In [9]:
num_heads = 4
d_k = d_model // num_heads

W_q = np.random.rand(d_model, d_k * num_heads)
b_q = np.random.rand(d_k * num_heads)
W_k = np.random.rand(d_model, d_k * num_heads)
b_k = np.random.rand(d_k * num_heads)
W_v = np.random.rand(d_model, d_k * num_heads)
b_v = np.random.rand(d_k * num_heads)

Q = np.dot(encoder_input, W_q) + b_q
K = np.dot(encoder_input, W_k) + b_k
V = np.dot(encoder_input, W_v) + b_v

display(Q)
display(K)
display(V)

array([[[29.99963455, 31.39468792, 36.41321779, ..., 38.67696626,
         31.9077041 , 34.53522034],
        [30.14404508, 32.01325538, 36.55477684, ..., 39.01446621,
         32.26408133, 34.63407949],
        [28.1261651 , 31.78523931, 36.24716601, ..., 36.91157407,
         33.08587588, 33.79151011],
        ...,
        [25.75813423, 27.41629856, 33.436441  , ..., 36.28046813,
         29.59257487, 33.23711392],
        [24.23982182, 27.74043209, 29.61175121, ..., 34.32011225,
         27.7755896 , 28.86495413],
        [26.03314029, 28.52109521, 31.44633713, ..., 36.77699308,
         29.37421814, 32.22384072]],

       [[28.50072472, 30.28113247, 30.68180127, ..., 35.96114461,
         29.43462302, 31.45060211],
        [28.89713431, 31.40240984, 33.16687976, ..., 36.70342144,
         30.79362487, 31.63260783],
        [28.91878071, 31.72192919, 36.04852398, ..., 38.17840407,
         32.01084934, 34.07880718],
        ...,
        [27.49838372, 28.24536636, 30.94641284, ..., 3

array([[[32.43295047, 34.31954948, 33.37356033, ..., 33.84562942,
         33.6941413 , 31.98878564],
        [34.02833075, 35.02704572, 34.90693726, ..., 33.33909051,
         36.11646659, 33.32663608],
        [31.92580727, 32.48242387, 34.10898735, ..., 34.41489007,
         33.66381359, 31.57362302],
        ...,
        [31.06279468, 31.14749279, 36.01708262, ..., 31.86662893,
         30.86177249, 32.11040998],
        [28.85330088, 28.49333672, 33.63441287, ..., 30.34835249,
         29.80102129, 30.1851772 ],
        [31.09127379, 29.12154194, 32.63186734, ..., 31.32719731,
         31.144186  , 30.07952407]],

       [[30.76973086, 31.30081525, 31.42988275, ..., 31.29606301,
         30.75411252, 31.24855569],
        [32.00718393, 32.88952624, 33.76995542, ..., 32.61578381,
         32.1115807 , 32.11968969],
        [32.80348565, 34.43780324, 36.33251384, ..., 34.88276041,
         34.43269155, 33.65716956],
        ...,
        [30.54762042, 28.92711145, 34.5219544 , ..., 3

array([[[37.48107635, 29.28129313, 35.53957082, ..., 37.62545956,
         34.9526233 , 34.28770192],
        [36.312094  , 31.48892341, 36.70991266, ..., 39.01366718,
         36.01374078, 38.82423372],
        [35.19360919, 29.10943205, 35.10817913, ..., 36.18833788,
         34.43751179, 36.90233876],
        ...,
        [34.23867447, 27.99396397, 33.03277779, ..., 36.31754256,
         31.54606281, 33.97731583],
        [33.195128  , 25.13372825, 31.78091037, ..., 35.56238383,
         30.25210816, 32.73112055],
        [34.50620417, 27.84018686, 32.99341291, ..., 37.85826354,
         31.38653967, 32.25065442]],

       [[34.3454721 , 28.42126368, 34.08715131, ..., 35.8718449 ,
         31.51779765, 31.29250865],
        [35.60632419, 28.90384211, 34.22037512, ..., 37.10844968,
         33.00575717, 34.97135973],
        [38.17945525, 30.58893266, 36.8944488 , ..., 38.50686893,
         35.16237897, 37.26426102],
        ...,
        [34.70681075, 28.53732668, 32.21163038, ..., 3

In [10]:
heads_output = []
for i in range(num_heads):
    head_Q = Q[:, :, i * d_k : (i + 1) * d_k]
    head_K = K[:, :, i * d_k : (i + 1) * d_k]
    head_V = V[:, :, i * d_k : (i + 1) * d_k]

    scores = np.matmul(head_Q, head_K.transpose(0, 2, 1)) / np.sqrt(d_k)
    attention_weights = softmax(scores)
    head_output = np.matmul(attention_weights, head_V)
    heads_output.append(head_output)

multi_head_output = np.concatenate(heads_output, axis=-1)

W_o = np.random.rand(d_model, d_model)
b_o = np.random.rand(d_model)
attention_output = np.dot(multi_head_output, W_o) + b_o

display(attention_output)

array([[[1004.01646407,  876.10970746, 1140.99069721, ...,
         1017.30716589, 1094.35693359,  980.79634228],
        [1004.01646407,  876.10970746, 1140.99069721, ...,
         1017.30716589, 1094.35693359,  980.79634228],
        [1004.01646407,  876.10970746, 1140.99069721, ...,
         1017.30716589, 1094.35693359,  980.79634228],
        ...,
        [1004.01646407,  876.10970746, 1140.99069721, ...,
         1017.30716589, 1094.35693359,  980.79634228],
        [1004.01646407,  876.10970746, 1140.99069721, ...,
         1017.30716589, 1094.35693359,  980.79634228],
        [1004.01646407,  876.10970746, 1140.99069721, ...,
         1017.30716589, 1094.35693359,  980.79634228]],

       [[ 997.42419457,  862.47441889, 1132.40786222, ...,
         1009.79596174, 1083.72168941,  969.8849466 ],
        [ 997.42419457,  862.47441889, 1132.40786222, ...,
         1009.79596174, 1083.72168941,  969.8849466 ],
        [ 997.42419457,  862.47441889, 1132.40786222, ...,
         1009.

In [11]:
gamma_ln1 = np.random.rand(d_model)
beta_ln1 = np.random.rand(d_model)

attention_add = encoder_input + attention_output

attention_norm_output = layer_norm(attention_add, gamma_ln1, beta_ln1)

display(attention_norm_output)

array([[[-0.34150086, -0.63474235,  0.74826169, ..., -0.01807262,
          0.7003567 , -0.12971714],
        [-0.33383008, -0.64049483,  0.75248414, ..., -0.01832047,
          0.6934496 , -0.13093692],
        [-0.33450597, -0.6419281 ,  0.7554043 , ..., -0.01811944,
          0.69137946, -0.13037262],
        ...,
        [-0.33412843, -0.6359645 ,  0.74126224, ..., -0.01850892,
          0.70282778, -0.12940198],
        [-0.33309676, -0.64505062,  0.74102696, ..., -0.01810547,
          0.70406946, -0.129173  ],
        [-0.33883524, -0.64805831,  0.75051125, ..., -0.01811135,
          0.69760464, -0.12270107]],

       [[-0.3219356 , -0.67274143,  0.7550875 , ..., -0.01719423,
          0.6852165 , -0.13789614],
        [-0.31423591, -0.67740251,  0.76062896, ..., -0.01691109,
          0.68865468, -0.13873768],
        [-0.3124884 , -0.6821609 ,  0.76496812, ..., -0.01708807,
          0.68496865, -0.14216857],
        ...,
        [-0.31711444, -0.67302458,  0.75519307, ..., -

In [12]:
d_ff = 2048

W_ff1 = np.random.rand(d_model, d_ff)
b_ff1 = np.random.rand(d_ff)
W_ff2 = np.random.rand(d_ff, d_model)
b_ff2 = np.random.rand(d_model)

ffn_output_inner = np.maximum(0, np.dot(attention_norm_output, W_ff1) + b_ff1)

ffn_output = np.dot(ffn_output_inner, W_ff2) + b_ff2

display(ffn_output)

array([[[16500.29325544, 16936.59739553, 16577.88626977, ...,
         16564.25862664, 16074.75486345, 16610.6723561 ],
        [16497.76125806, 16933.76948746, 16575.21783426, ...,
         16561.64299548, 16072.19277979, 16608.02885775],
        [16499.76270394, 16935.69061267, 16576.86761928, ...,
         16563.41299919, 16074.00390746, 16609.79126849],
        ...,
        [16495.98767752, 16932.06994019, 16573.40020275, ...,
         16559.87250078, 16070.82234637, 16606.34771929],
        [16495.63523881, 16931.64126169, 16573.15297081, ...,
         16559.31170989, 16070.29535467, 16605.93291046],
        [16485.45571575, 16921.37455905, 16563.10953659, ...,
         16549.22900096, 16060.49273114, 16595.65277861]],

       [[16469.48492898, 16905.4242188 , 16546.40124472, ...,
         16530.96520675, 16044.557074  , 16579.4638808 ],
        [16468.87071363, 16904.39398881, 16545.61263288, ...,
         16530.08204018, 16043.75111149, 16578.72575681],
        [16472.68081838, 

In [13]:
gamma_ln2 = np.random.rand(d_model)
beta_ln2 = np.random.rand(d_model)

encoder_output_add = attention_norm_output + ffn_output

encoder_output = layer_norm(encoder_output_add, gamma_ln2, beta_ln2)

display(encoder_output)

array([[[ 0.36367029,  1.25427652,  0.63380522, ...,  0.62279376,
         -0.83369911,  0.83634869],
        [ 0.36404955,  1.25383347,  0.633768  , ...,  0.6228093 ,
         -0.83375034,  0.8363242 ],
        [ 0.36462977,  1.25384379,  0.63355805, ...,  0.62256183,
         -0.83376894,  0.83613253],
        ...,
        [ 0.36333537,  1.25386561,  0.63357714, ...,  0.62245715,
         -0.83344381,  0.83624806],
        [ 0.3640994 ,  1.2541794 ,  0.63384438, ...,  0.62238573,
         -0.83347217,  0.83644221],
        [ 0.36343668,  1.25426644,  0.63388817, ...,  0.6223588 ,
         -0.83354651,  0.83615545]],

       [[ 0.36550101,  1.2569575 ,  0.63370869, ...,  0.61813964,
         -0.83348026,  0.83672238],
        [ 0.36666974,  1.25646798,  0.63379522, ...,  0.61812087,
         -0.8333169 ,  0.83694578],
        [ 0.36682128,  1.25655611,  0.63380939, ...,  0.61852275,
         -0.83331634,  0.83697322],
        ...,
        [ 0.36553777,  1.2569708 ,  0.63380943, ...,  